name: failure-workflow

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  fail:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: exit 1
  comment:
    permissions:
      pull-requests: write
    if: failure() && github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Write comment to PR
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            :wave: This is a PR to the default branch
            It looks like this job might have failed :frowning:
            See details about this job in the [log](${{ github.event.pull_request.head.repo.html_url }}/actions/runs/${{ github.run_id }}).
